from snakemake.utils import validate


configfile: "config/config.yaml"


validate(config, schema="schemas/config.schema.yaml")


wildcard_constraints:
    seqrepo=r"(seqrepo|seqrepo_fixed)",
    assembly=r"(GRCh37|GRCh38)",
    source=r"(refseq|ensembl)",


include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/cdot.smk"
include: "rules/seqrepo.smk"
include: "rules/txdb.smk"
include: "rules/validate.smk"


rule all:
    input:
        expand(
            [
                "results/{alias}/datavzrd-report/{seqrepo}",
            ],
            alias=["GRCh37-refseq", "GRCh38-refseq"],
            seqrepo=["seqrepo_fixed"],
        ),
