# reference sequence definitions
reference:
  GRCh38:
    ensembl:
      species: homo_sapiens
      release: 110
      build: GRCh38
      datatype: cdna
    refseq:
      species: H_sapiens
      species_name: human
  GRCh37:
    ensembl:
      species: homo_sapiens
      release: 105
      build: GRCh37
      datatype: cdna
    refseq:
      species: H_sapiens
      species_name: human


# cdot transcript sources for the references defined above
transcripts:
  GRCh38:
    cdot:
      release: 0.2.25
      custom: GCF_000001405.40_GRCh38.p14_genomic.110.gff
    # for the following set of transcripts, check against nuccore whether the CDS region is correct
    fix_cds: [
      # CASP8AP2
      "NM_001137667.2",
      "NM_001137668.2",
      "NM_012115.4",
      # DAG1
      "NM_001177639.3",
      # FOXO6
      "NM_001291281.3",
      # POLK
      "NM_001345921.3",
      "NM_001345922.3",
      "NM_001372044.2",
      "NM_001387110.3",
      "NM_001387111.3",
      "NM_001395899.1",
      "NM_001395901.1",
      "NM_001395902.1",
      "NM_016218.6",
      # SAMD1
      "NM_138352.3",
      # MUC19
      "NM_173600.2",
      # older versions in cdot than available in the current cdna ref releases:
      "NM_001401501.1",
      "NM_002457.4",
      "NM_003890.2",
      "NM_012234.6",
      "NM_017940.6",
    ]
    add_from_ensembl: [
      # Invalid CDS length in cdot:
      # Most (or all?) of these are marked as CDS join(a..b,c..d) in nuccore
      "NM_001172437.2",
      "NM_001184961.1",
      "NM_015068.3",
      "NM_182705.2",
      "NM_001145051.2",
      "NM_001301020.1",
      "NM_004152.3",
      "NM_001301302.1",
      "NM_002537.3",
      "NM_001134939.1",
      "NM_001301371.1",
      "NM_016178.2",
      "NM_053005.5",
    ]

  GRCh37:
    cdot:
      release: 0.2.25
      custom: GCF_000001405.25_GRCh37.p13_genomic.105.20201022.gff
    fix_cds: [
      # TODO: transcript retrieval for GRCh37, uses a dummy value atm
      "NM_182705.2",
    ]
  # the following entry is semi hardcoded for now
  # (rules::cdot::cdot_chrMT expects 'GRCh38-ensembl' to be defined)
  GRCh38-ensembl:
    cdot:
      release: 0.2.25
      custom: ensembl.grch38


# HGNC complete set file to check missing HGNC ids from cdot against
hgnc:
  # prefer quarterly versions, as these are stored indefinitely, while monthly versions are deleted after 1 year
  # format: yyyy-mm-dd
  # quarterly versions: yyyy-01-01, yyyy-04-01, yyyy-07-01, yyyy-10-01
  version: "2024-04-01"

  # In the case of "create", generate an artificial cdot file from the hgnc complete set.
  # In the case of "update" use the provided cdot file and update its transcripts with missing hgnc ids
  # with those from the complete set
  cdot-mode: update


# namespaces to use for seqrepo
namespaces:
  ensembl: Ensembl
  refseq: NCBI


# mehari version to use (currently ignored)
mehari:
  version: 0.26.0
