__use_yte__: true

datasets:
  mehari_check_db_stats:
    path: ?input.mehari_check_db_stats
    separator: "\t"
  cdot_hgnc_update:
    path: ?input.cdot_hgnc_update
    separator: "\t"
  fix_incorrect_entries:
    path: ?input.fix_incorrect_entries
    separator: "\t"
  refseq_id_to_ensembl_id:
    path: ?input.refseq_id_to_ensembl_id
    separator: "\t"
views:
  mehari_check_db_stats:
    dataset: mehari_check_db_stats
    render-table:
      columns:
        source:
          display-mode: normal
        kind:
          display-mode: normal
        reason:
          display-mode: normal
        len:
          display-mode: normal
  cdot_hgnc_update:
    dataset: cdot_hgnc_update
    render-table:
      columns:
        type:
          display-mode: normal
        key:
          display-mode: normal
        hgnc_id:
          display-mode: normal
  fix_incorrect_entries:
    dataset: fix_incorrect_entries
    render-table:
      columns:
        accession:
          display-mode: normal
        change:
          display-mode: normal
        start_codon:
          display-mode: normal
        stop_codon:
          display-mode: normal
  refseq_id_to_ensembl_id:
    dataset: refseq_id_to_ensembl_id
    render-table:
      columns:
        RefSeq mRNA ID:
          display-mode: normal
        Gene stable ID:
          display-mode: hidden
        Gene stable ID version:
          display-mode: normal
        Transcript stable ID:
          display-mode: hidden
        Transcript stable ID version:
          display-mode: normal
        HGNC ID:
          display-mode: normal
