channels:
  - conda-forge
  - nodefaults
dependencies:
  - curl ==7.87.0
  - wget ==1.21.4
  - grep ==3.11
  - python =3.12
  - requests ==2.32.3
  - gzip ==1.13
  - coreutils ==9.5
  - jq ==1.7.1
  - miller =6.13
  - pigz =2.8
